### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by quackduck** [thesephist/unim.press#7]
This is such a cool project, Linus!

I tried it out, but it seems it's stuck on loading posts from reddit?

**Comment by thesephist** [comment]
It's probably not down, but just having issues loading the particular subreddit. It was a quick hack and doesn't have very good error handling, so if you try to load a private subreddit or a banned / nonexistent one, it'll just hang without giving you an error.

Try loading the main page `https://unim.press/` and if it still doesn't load, maybe check your adblocker? Ad blockers sometimes block direct requests to reddit API.

**Comment by quackduck** [comment]
It's just stuck loading, even on the main page

**Comment by thesephist** [comment]
For me to really troubleshoot this, you'll have to give me what the Network pane in your browser's developer tools shows. What is the request to the Reddit API responding with? Also — as I asked above, are you positive you don't have an ad blocker blocking the page's requests to Reddit?

Without a way to re-create the problem on my side and/or knowing why requests to Reddit seem to be failing for you, I can't help you out here :/
